broker:
  user: slurm
  pw: Efxnag6Um_w4
  host: kleist1.informatik.uni-leipzig.de
  port: 1883
  qos: 1


defaults:
  time_voltage: 140
  time_current: 140
  averaging: 1 #Averaging disabled: all samples are collected individually.



instances:
  FAMLEM2:
    i2c_speed: 1000000
    usb_device_index: 1
    serial_number: 8283300
    system_under_measurement: curie02
    busses:
      bus0:
        - RAMlinksUnten
        - RAMlinksMitte
        - SSD12V
        - SSD5V
        - CPU12V
        - RAMrechtsMitte
        - RAMrechtsUnten
      bus1:
        - MoBo12V
        - MoBo5V
        - MoBo3V
      bus2: null
    inas:
      RAMlinksUnten:
        device_id: D
        address:
          a1: GND
          a0: VS
        r_shunt: 0.005
      RAMlinksMitte:
        device_id: C
        address:
          a1: VS
          a0: GND
        r_shunt: 0.005
      SSD12V:
        device_id: A
        address:
          a1: GND
          a0: SCL
        r_shunt: 0.105
      SSD5V:
        device_id: B
        address:
          a1: GND
          a0: SDA
        r_shunt: 0.105
      CPU12V:
        device_id: F
        address:
          a1: VS
          a0: VS
        r_shunt: 0.005
      RAMrechtsMitte:
        device_id: G
        address:
          a1: GND
          a0: GND
        r_shunt: 0.005
      RAMrechtsUnten:
        device_id: H
        address:
          a1: SDA
          a0: GND
        r_shunt: 0.005
      MoBo12V:
        device_id: I
        address:
          a1: GND
          a0: VS
        r_shunt: 0.017
      MoBo5V:
        device_id: J
        address:
          a1: VS
          a0: SDA
        r_shunt: 0.030
      MoBo3V:
        device_id: K
        address:
          a1: VS
          a0: SCL
        r_shunt: 0.030
  FAMLEM1:
    i2c_speed: 1000000
    usb_device_index: 0
    serial_number: 6234610
    system_under_measurement: curie01
    busses:
      bus0:
        - MOBO_1_3_3V
        - MOBO_2_3_3V
        - MOBO_4_5V
        #- MOBO_6_5V
        - MOBO_10_12V
        - MOBO_11_12V
        - MOBO_12_3_3V
        - MOBO_13_3_3V
        - MOBO_21_5V
        - MOBO_22_5V
        - MOBO_23_5V
      bus1: null
      bus2:
        - CPU_1_12V
        - CPU_2_12V
        - SSD_YELLOW_12V
        #- MOBO_6_5V
        - SSD_RED_5V
    #An INA's address corresponds to its A0/A1 pin connections on the chip's backside.
    #MOBO voltage depends on the INA's position in the ATX12V 2.x power supply connector,
    #(in the 15 pin Serial Ata Power Connector for SSD voltage).
    #r_shunt = shunt resistor value.
    #Device IDs can be assigned deliberately.
    inas:
      CPU_1_12V:
        device_id: A
        address:
          a1: GND
          a0: GND
        max_current: 2
        r_shunt: 0.1
      CPU_2_12V:
        device_id: B
        address:
          a1: GND
          a0: VS
        max_current: 2
        r_shunt: 0.1
      MOBO_1_3_3V:
        device_id: C
        address:
          a1: GND
          a0: SDA
        max_current: 2
        r_shunt: 0.1
      MOBO_2_3_3V:
        device_id: D
        address:
          a1: VS
          a0: VS
        max_current: 2
        r_shunt: 0.1
      MOBO_4_5V:
        device_id: E
        address:
          a1: SCL
          a0: VS
        max_current: 2
        r_shunt: 0.1
      MOBO_6_5V:
        device_id: F
        address:
          a1: GND
          a0: GND
        max_current: 2
        r_shunt: 0.1
      MOBO_10_12V:
        device_id: G
        address:
          a1: VS
          a0: VS
        max_current: 2
        r_shunt: 0.1
      MOBO_11_12V:
        device_id: H
        address:
          a1: SDA
          a0: GND
        max_current: 2
        r_shunt: 0.1
      MOBO_12_3_3V:
        device_id: I
        address:
          a1: VS
          a0: GND
        max_current: 2
        r_shunt: 0.1
      MOBO_13_3_3V:
        device_id: J
        address:
          a1: VS
          a0: SDA
        max_current: 2
        r_shunt: 0.1
      MOBO_21_5V:
        device_id: K
        address:
          a1: GND
          a0: GND
        max_current: 2
        r_shunt: 0.1
      MOBO_22_5V:
        device_id: L
        address:
          a1: SCL
          a0: GND
        max_current: 2
        r_shunt: 0.1
      MOBO_23_5V:
        device_id: M
        address:
          a1: SDA
          a0: VS
        max_current: 2
        r_shunt: 0.1
      SSD_YELLOW_12V:
        device_id: N
        address:
          a1: SDA
          a0: SDA
        max_current: 2
        r_shunt: 0.1
      SSD_RED_5V:
        device_id: O
        address:
          a1: VS
          a0: GND
        max_current: 2
        r_shunt: 0.1

#Configurations in this file should reflect the current physical setup of the measurement system ('curie02').


#For changing around bus allocation, refer to "yaml_Belegungen" PDF.



